---
### Live profile
spring:
  config:
    use-legacy-processing: true
  profiles: live
  liquibase:
    enabled: false
  datasource:
    driver-class-name: ${spring.datasource.driver-class-name}
    username: ${spring.datasource.username.payment-batch}
    password: ${spring.datasource.password.payment-batch}
    url: ${spring.datasource.url.payment-batch}

backbase:
  communication:
    services:
      dbs:
        integration:
          external:
            outbound:
              paymentorder:
                batch:
                  service-id: payment-batch-core-mock

  payments:
    batches:
      approval:
        enabled: true
      supported-batch-upload-types:
        - BB_SEPACT_CSV
