-- new business functions
INSERT INTO BUSINESS_FUNCTION(ID, FUNCTION_CODE, FUNCTION_NAME, RESOURCE_CODE, RESOURCE_NAME)
VALUES
('1078', 'manage.authorized.users', 'Manage Authorized Users', 'user', 'User');

INSERT INTO APPLICABLE_FUNCTION_PRIVILEGE
(ID, BUSINESS_FUNCTION_NAME, FUNCTION_RESOURCE_NAME, PRIVILEGE_NAME, SUPPORTS_LIMIT, BUSINESS_FUNCTION_ID, PRIVILEGE_ID)
VALUES
('294', 'Manage Authorized Users', 'User', 'view', 1, '1078', '2');

INSERT INTO APPLICABLE_FUNCTION_PRIVILEGE
(ID, BUSINESS_FUNCTION_NAME, FUNCTION_RESOURCE_NAME, PRIVILEGE_NAME, SUPPORTS_LIMIT, BUSINESS_FUNCTION_ID, PRIVILEGE_ID)
VALUES
('295', 'Manage Authorized Users', 'User', 'create', 1, '1078', '3');

INSERT INTO APPLICABLE_FUNCTION_PRIVILEGE
(ID, BUSINESS_FUNCTION_NAME, FUNCTION_RESOURCE_NAME, PRIVILEGE_NAME, SUPPORTS_LIMIT, BUSINESS_FUNCTION_ID, PRIVILEGE_ID)
VALUES
('296', 'Manage Authorized Users', 'User', 'edit', 1, '1078', '4');

INSERT INTO ASSIGNABLE_PERMISSION_SET_ITEM
(ASSIGNABLE_PERMISSION_SET_ID, FUNCTION_PRIVILEGE_ID)
VALUES
(1, '294');

INSERT INTO ASSIGNABLE_PERMISSION_SET_ITEM
(ASSIGNABLE_PERMISSION_SET_ID, FUNCTION_PRIVILEGE_ID)
VALUES
(1, '295');

INSERT INTO ASSIGNABLE_PERMISSION_SET_ITEM
(ASSIGNABLE_PERMISSION_SET_ID, FUNCTION_PRIVILEGE_ID)
VALUES
(1, '296');

COMMIT;