update legal_entity set parent_id=null;
delete from approval_function_group_item;
delete from approval_add_prop_sa;
delete from approval_service_agreement_aps;
delete from approval_sa_admins;
delete from approval_sa_participant;
delete from approval_service_agreement;
delete from approval_function_group;
delete from approval_uc_assign_fg_dg
delete from approval_uc_assign_fg;
delete from user_assigned_combination_dg;
delete from user_assigned_fg_combination;
delete from user_assigned_function_group;
delete from add_prop_service_agreement;
delete from user_context;
delete from function_group_item;
delete from function_group;
delete from approval_uc_assign_fg_dg;
delete from data_group_item;
delete from participant_user;
delete from add_prop_legal_entity;
delete from legal_entity_ancestor;
delete from data_group;
delete from sa_admin;
delete from participant;
delete from assignable_permission_set_item where assignable_permission_set_id>2;
delete from service_agreement_aps;
delete from sequence_table;
delete from approval_data_group_item;
delete from assignable_permission_set where id>2;
delete from service_agreement;
delete from legal_entity;
delete from approval_data_group_detail;
delete from approval_data_group;
delete from approval_user_context;
delete from approval_function_group_ref;
delete from approval_service_agreement_ref;
delete from access_control_approval;