---
### Live profile
spring:
  profiles: live
  datasource:
    driver-class-name: ${spring.datasource.driver-class-name}
    username: ${spring.datasource.username.user-manager}
    password: ${spring.datasource.password.user-manager}
    url: ${spring.datasource.url.user-manager}
backbase:
  communication:
    services:
      user:
        profile:
          service-id: "user-integration-external-mock"
  security:
    mtls:
      enabled: false
    public:
      paths: "/**"
