---
### Live profile
spring:
  profiles: live
  cache:
    caffeine:
      spec: ${spring.cache.caffeine.spec.audit-service}
  datasource:
    driver-class-name: ${spring.datasource.driver-class-name}
    username: ${spring.datasource.username.audit-service}
    password: ${spring.datasource.password.audit-service}
    url: ${spring.datasource.url.audit-service}
