---
### Live profile
spring:
  profiles: live
  datasource:
    driver-class-name: ${spring.datasource.driver-class-name}
    username: ${spring.datasource.username.action-service}
    password: ${spring.datasource.password.action-service}
    url: ${spring.datasource.url.action-service}

