#
# Configuration file only for development
#
portal:
  resource-location:
    profile: filesystem
    path: ${BACKBASE_HOME}/portal/contextroot
  extension-points:
    enabled: true
  content:
    enabled: true

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/portal_draft?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

space-controller:
  enabled: true
  datasource:
    strategy: SWITCH_DATASOURCE
  space-filter:
    should-not-filter-paths: /actuator/**
  spaces:
    - id: draft
      datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/portal_draft?useSSL=false
        type: com.zaxxer.hikari.HikariDataSource
        username: root
        password: root
    - id: final
      datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/portal_final?useSSL=false
        type: com.zaxxer.hikari.HikariDataSource
        username: root
        password: root