### Common app properties
server:
  port: 8186
eureka:
  instance:
    metadata-map:
      public: true
      role: live
  client:
    serviceUrl:
      defaultZone: http://${REGISTRY_HOST:localhost}:${REGISTRY_PORT:8080}/registry/eureka/
spring:
  application:
    name: legalentity-integration-outbound-service
  profiles:
    active: ${DBS_ACTIVE_PROFILE:live}
  cloud:
    stream:
      default-binder: activemq

backbase:
  events:
    enabled: false
  persistence:
    enabled: false
  web:
    security:
      enabled: true
  usercontext:
    jwtTokenExpiration: 300
    signatureAndEncryption:
      key:
        type: ENV
        value: USERCTX_KEY
sso:
  jwt:
    internal:
      type: signed
      signature:
        key:
          type: ENV
          value: SIG_SECRET_KEY