#
# Configuration file only for development
#

spring:
  profiles:
    active: campaigns
  datasource:
    url: jdbc:mysql://localhost:3306/tar_draft?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

targeting:
  collectors:
    session:
      enabled: true
  campaigns:
    storage-interval: 0 0/1 * * * *
  extension-points:
    enabled: true

space-controller:
  enabled: true
  datasource:
    strategy: SWITCH_DATASOURCE
  space-filter:
    should-not-filter-paths: /actuator/**
  spaces:
    - id: draft
      datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/tar_draft?useSSL=false
        type: com.zaxxer.hikari.HikariDataSource
        username: root
        password: root
    - id: final
      datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/tar_final?useSSL=false
        type: com.zaxxer.hikari.HikariDataSource
        username: root
        password: root

management:
  endpoint:
    spaces:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,health,beans,spaces
  health:
    rabbit:
      enabled: false