---
### Live profile
spring:
  profiles: live
  datasource:
    driver-class-name: ${spring.datasource.driver-class-name}
    username: ${spring.datasource.username.accesscontrol-pandp-service}
    password: ${spring.datasource.password.accesscontrol-pandp-service}
    url: ${spring.datasource.url.accesscontrol-pandp-service}