---
### Live profile
spring:
  profiles: live
  datasource:
    driver-class-name: ${spring.datasource.driver-class-name}
    username: ${spring.datasource.username.contact-manager}
    password: ${spring.datasource.password.contact-manager}
    url: ${spring.datasource.url.contact-manager}

backbase:
  security:
    mtls:
      enabled: false
  contact:
    approval:
      enabled: true
