version: "3.1"
# https://docs.docker.com/compose/compose-file/

services:
  employeeApp:
    image: local-employee-app
    container_name: local-employee-app
    ports:
      - "8280:8080"
    environment:
      - API_ROOT=/api
      - AUTH_URL=http://localhost:8180/auth
      - AUTH_CLIENT_ID=bb-web-client
      - AUTH_REALM=LaurentianBank
      - AUTH_SCOPE=openid
