/*
 *
 *
 *
 *
 *
 *         WARNING: Editing this file may prevent future updates via schematics.
 *                  To maintain easy upgradability, do not edit this file.
 *
 *
 *
 *
 *
 */
import { HttpClientModule } from '@angular/common/http';
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { RouterModule, Routes } from '@angular/router';
import { EmployeeWebAppLayoutModule } from '@backbase/employee-web-app-shared-ui-layout';
import {
  EmployeeWebAppChromeComponent,
  EmployeeWebAppRootModule,
  SelectContextWrapperComponent,
  WorkspaceSwitcherModule,
} from '@backbase/employee-web-app-root-feature-app-shell';
import {
  EmployeeWebAppCoreModule,
  getWebSdkConfig,
} from '@backbase/employee-web-app-shared-util-core';
import {
  BackbaseCoreModule,
  DeprecationsService,
} from '@backbase/foundation-ang/core';
import { WebSdkModule } from '@backbase/foundation-ang/web-sdk';
import { environment } from '../environments/environment';
import { AppDataModules } from './app-data-modules';
import { appModuleImports } from './app-module-imports';
import { additionalRoutes, workspaceRoutes } from './app-module-routes';
import { AppComponent } from './app.component';

const routes: Routes = [
  ...additionalRoutes,
  {
    path: 'select-context',
    component: SelectContextWrapperComponent,
  },
  {
    path: '',
    component: EmployeeWebAppChromeComponent,
    children: [...workspaceRoutes],
  },
];

@NgModule({
  declarations: [AppComponent],
  imports: [
    EmployeeWebAppCoreModule.forRoot(environment),
    BackbaseCoreModule.forRoot({
      features: {
        NEW_COMMUNICATION_API_ENABLED: true,
        ...(environment.features || {}),
      },
      assets: environment.assetsConfig || {
        assetsStaticItemName: '',
      },
    }),
    HttpClientModule,
    AppDataModules,
    BrowserModule,
    BrowserAnimationsModule,
    RouterModule.forRoot(routes, {
      useHash: environment.useHashNavigation,
      paramsInheritanceStrategy: 'always',
      relativeLinkResolution: 'corrected',
    }),
    EmployeeWebAppRootModule,
    EmployeeWebAppLayoutModule,
    WebSdkModule.forRoot(getWebSdkConfig(environment)),
    WorkspaceSwitcherModule,
    ...appModuleImports,
  ],
  providers: [DeprecationsService, ...(environment.providers || [])],
  bootstrap: [AppComponent],
})
export class AppModule {}
