---
### Live profile
spring:
  profiles: live
  datasource:
    driver-class-name: ${spring.datasource.driver-class-name}
    username: ${spring.datasource.username.arrangement-manager}
    password: ${spring.datasource.password.arrangement-manager}
    url: ${spring.datasource.url.arrangement-manager}
backbase:
  communication:
    services:
      account:
        integration:
          service-id: account-mock
  arrangement:
    alias:
      journey: ACCOUNT_ALIAS
